config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to:'blog#index'

  resources :blog, :user, :profile
  
  resources :blog do
    resources :comment, only: [:create, :destroy,:edit]
  end

  post "/blog/comments", to:"blog#create_comment"
  get "/user/profile", to: "user#index"
  
  get "/logout", to: "login#logout"
  get "/login", to: "login#index"
  post "/login", to: "login#check_credentials"
  # post "/blog", to: "blog#create_comment"




  get "/search", to: "blog#blogSearch"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user, foreign_key: :user_id
    has_many :comments, dependent: :destroy
    has_many_attached :images
    has_rich_text :content
    # validates :blog_title, :blog_author, presence:true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :comment, presence: true
    belongs_to :user, foreign_key: :user_id
    belongs_to :blog,foreign_key: :blog_id
end

app/models/user.rb
class User < ApplicationRecord
    # devise :database_authenticatable, :recoverabe, :rememberable
    has_many :blogs
    has_one_attached :avatar
    
    validates :username, presence:true
    validates :email, uniqueness:true
    validates :password, :length =>{ :minimum => 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user    
        return User.find_by(id: session[:user_id])  
        
    end

    def isLogged_in
       
        return !current_user.nil?  
    end


    helper_method :current_user
    helper_method :isLogged_in
    # def current_user
    # User.find_by(id: session[:user_id])
    # end
    # def logged_in?
        
    #     !current_user.nil?
    # end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

    def index
        
        @user = User.joins(:blogs)
        @blog = Blog.joins(:user)
        @Comment =Comment.all


        
        

    end
    
   

    def create_comment
        @comment =Comment.new(params.require(:comment).permit(:comment,:user_id,:blog_id))

        if @comment.save!

            flash[:comment_saved] = ["your comment has been saved"]
            redirect_to "/blog"
        end
    end

    def show

        if current_user.nil?
            flash[:login_restrict] = ["User must login first"]
            redirect_to "/blog"
        else
        
        @blog = Blog.find(params[:id])
       
        user_id = @blog.user_id
       
        @user = User.find(user_id)
        end
    end


    def create 
        
        blog = Blog.new(params.require(:blog).permit(:blog_title,:content, :blog_author,:user_id))
        if blog.save!
            redirect_to blog_index_path
        else
            flash[:blog_errors] = ["Unable to create Blog"]  
            render :new
        end
    end

    def edit
    @blog = Blog.find(params[:id])
    
    end

    def update
        blog=Blog.find(params[:id])
        blog.update(params.require(:blog).permit(:blog_title,:content, :blog_author,:user_id))
        if blog.save!
            redirect_to blog_index_path
        else
            flash[:blog_errors] = ["Unable to Update Blog"]  
            render :new
        end
    end

    def new
       blog = Blog.new 
    end

    def destroy
        
        @blog = Blog.find(params[:id]).destroy

        redirect_to blog_index_path
    
    end


    # Blog Search Functionality
    def blogSearch

        searchKey = params[:query]

        @searchedBlog = Blog.where('blog_title like ? OR blog_author like ?',"%#{searchKey}%","%#{searchKey}%")
        render "search"
    end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController

def index

   
end

def check_credentials

    @uname = User.pluck(:username)
    @pass = User.pluck(:password)
    @username = params[:username]
    @password = params[:password]

   
    
    if (@uname.include? @username) && (@pass.include? @password)
        @user = User.find_by!(:username => @username,:password =>@password)  

        session[:user_id] = @user.id
        redirect_to "/blog"

     else 
        reset_session
        flash[:login_errors] = ["Invalid credentials"]
        redirect_to "/login"
    end

    

end
def logout
    # session[:user_id].
    reset_session  

    if session[:user].nil?
        flash[:logout_msg] = ["Successfully logout"]
        
    end
    redirect_to "/login" 

    
end

private 
    def login_params
        params.require(:login).permit(:username, :password)
            
    end



end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

def show
    username = request.path_parameters.values
    @user = User.find_by(:username => username[2])



    @blog = Blog.where(:blog_author => username[2])

    

    
end

end

app/controllers/register_controller.rb
class RegisterController < ApplicationController

    def create
       
        @user = User.new(params.require(:register).permit(:username, :email, :password,:gender,:fb_link,:insta_link,:age,:twitter_link,:stack_overflow_link,:address,:job, :phone_number,:avatar ))
        puts @user.valid?
        if(@user.save)

            flash[:user_created_msg] = ["User has been created successfully"]
            redirect_to "/login"
        else
            
            # flash[:user_creation_failure_msg] = ["Some thing went wrong"]
            redirect_to "/register"
        end
    end


end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def index
        
        
    end

    def create
        
        
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper

    def comment_on_specific_blog(blog_id)
        @comments= Comment.where(:blog_id=>blog_id).order("created_at DESC")
        
        return @comments
      end

      def find_UserbyCommentID(user_id)
        @user = User.where(:id=>user_id)
        return @user.first;
      end


      def delete_comment(comment_id)
      
        @comment = Comment.where(:id=>comment_id)
      
      end

      def edit_comment(comment_id,new_comment)
      
        @comment = Comment.update(:id=>comment_id, :comment=>new_comment)
      
      end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog/_form.html.erb
<div class = "container">

    <div class = "row mt-5 text-light" >
    
        <div class = "col-mdd-4 d-fex justify-content-center mt-5 pt-5 nav-color ">
            <%= form_for :blog,url:{ action: :create },  method: :post do |f| %>
                
                <div class="d-flex py-4" >
                    Title <%= f.text_field :blog_title , :class => "form-control w-25 mx-3"%>
                     <%= f.text_field :blog_author,:type=>"hidden", :value =>current_user.username  %>
                    <%= f.number_field :user_id,:type=>"hidden",:value =>current_user.id %>
                </div>
                <div class="field">
                    <%= f.label :content %>
                    <%= f.rich_text_area :content %>
                </div>
                <%= f.submit  :class => "btn btn-outline-success my-3"%>
            <% end %>
            <%if flash[:blog_errors]%>
                <% flash[:blog_errors].each do |msg| %>
                    <div class="alert alert-danger">
                        <%= msg %>
                    </div>
                <% end %>
            <%end%>
        
        
        </div>
    
    </div>

</div>

app/views/blog/edit.html.erb
<div class = "container">

    <div class = "row mt-5 text-light" >
    
        <div class = "col-mdd-4 d-fex justify-content-center mt-5 pt-5 nav-color ">
            <%= form_for :blog,url:{ action: :edit },  method: :patch do |f| %>
                
                <div class="d-flex py-4" >
                    Title <%= f.text_field :blog_title , :class => "form-control w-25 mx-3"%>
                     <%= f.text_field :blog_author,:type=>"hidden", :value =>current_user.username  %>
                    <%= f.number_field :user_id,:type=>"hidden",:value =>current_user.id %>
                </div>
                <div class="field">
                    <%= f.label :content %>
                    <%= f.rich_text_area :content %>
                </div>
                <%= f.submit  :class => "btn btn-outline-success my-3"%>
            <% end %>
            <%if flash[:blog_errors]%>
                <% flash[:blog_errors].each do |msg| %>
                    <div class="alert alert-danger">
                        <%= msg %>
                    </div>
                <% end %>
            <%end%>
        
        
        </div>
    
    </div>

</div>

app/views/blog/index.html.erb
<div class = "container-fluid mt-4 pt-5">
  <div class= "row">
    <div class="col-md-3  shadow-lg rounded recent-blog "  >
      <%
      if session[:user_id].nil?%>
        
      <%else%>
            <%=link_to "Create Blog", new_blog_path, :class => "btn btn-outline-primary col-md-12 my-3"%>  
      <%end%>
      <%if flash[:login_restrict]%>
        <% flash[:login_restrict].each do |msg| %>
            <div class="alert alert-danger my-2">
                <%= msg %>
            </div>
        <% end %>
      <%end%>
      <hr>
      <h4>Recent Blogs<hr></h4>
      <div style="overflow:scroll; height:400px;">
        <% @blog.each do |blog| %>
          <% if @blog.nil? %>
            <p>No any blog created.... </p>
          <% else %>
            <ul>
            <%# This code gives helps me to give user avaatar of the user %>
                <%
                  user_id = blog.user_id
                  user = User.find(user_id)

                %>
              <div class=" "> 
                <kbd><%=link_to blog.blog_title , blog, :class => "text-decoration-none text-light "%>(<%=blog.created_at.strftime('%b %d, %Y')%>)</kbd><br>
                <div class="small badge badge-white  text-dark border  "><img src="<%=url_for(user.avatar)%>" class="profile-img-sm"><%=blog.blog_author%></div>
              </div>
            </ul>
          <% end %>
        <% end %>
      </div>
    </div>
    
    <div class="col-md-9   ">
      <div class = "">
        
        <div class= "">
          <div class = "col-md-12 overflow-auto">
            <div class = "row">
            <div class= "col-md-12 " style="overflow:scroll; height:500px;">
              
              <% @blog.each do |blog| %>
                <div class = "col-md-12  " >
                <%
                  user_id = blog.user_id
                  user = User.find(user_id)

                %>
                  <div class = "card  rounded shadow" id="box"  >
                    <div class = "card-header header-color">
                      <div class="inner p-1 "  >
                        <div class="inner-p bg-light p-2">
                          <h3 class="text-success "><%=blog.blog_title%></h3>
                          <p>
                          <img src="<%=url_for(user.avatar)%>" class="profile ">
                            <span class=" mx-1 text-dark border rounded p-1">
                              
                              <%=link_to blog.blog_author, profile_path(blog.blog_author), :class => "text-decoration-none text-uppercase text-dark"%> (<%=user.job%>)
                              
                            </span>
                            <%#  Lets suppose a person can read upto 50 words per minute%>
                            <%minute= blog.content.to_plain_text.scan(/[\w-]+/).size/50
                            if minute>=60
                              minute = minute%60
                              hour = minute/60 

                            end
                              
                            %>
                            <span class="badge badge-primary mx-1 bg-success text-light border border-brand-green "><i class="fas fa-book-reader text-light"></i> 
                            
                            <%=minute%>&nbsp;Min. Read</span>
                            <span class="badge badge-primary mx-1 bg-primary text-light "><i class="fas fa-calendar-alt text-light"></i> <%=blog.created_at.strftime('%b %d, %Y')%></span>
                            
                          </p>
                        </div>
                      </div>
                    </div>

                      
                    <div class="trix-content card-body m-0">
                      
                      <div class="">
                        <%=blog.content.to_plain_text.truncate_words(50)%>
                      
                      </div>

                                                                
                      
                      <div class="">
                      
                        <div ><%=link_to "Read More", blog, :class => "text-success d-flex mx-4 justify-content-end text-decoration-none "%>
                        </div>
                        
                        <%if isLogged_in && (current_user.id)== blog.user_id%>  
                          <div class="">
                            <%= link_to '', blog_path(blog), :class => "fa fa-trash text-danger text-right ",
                            method: :delete,
                            data: { confirm: 'Are You sure?' } %>
                            <%=link_to "", edit_blog_path(blog.id), :class => "text-secondary fa fa-edit text-decoration-none mx-3"%>
                                             
                          </div>

                        <%end%>
                        

                        <hr>
                        <div class="col-md-12">
                        <div id="like_cmnt_show " class="row text-center" >
                          
                            <div class="col-md-6 col-sm-6 col-lg-6">
                              <span id="likes<%=blog.id%>"></span> likes
                            </div>

                            <div id=<%=blog.id%> class="show-more-comment  col-md-6 col-sm-6 col-lg-6"><%=comment_on_specific_blog(blog.id).count%> comments</div>
                          
                          </div>
                        </div>
                        <hr>
                        
                        <%if isLogged_in%>
                          
                            <%=render "partials/like_comment_share" ,{blog_id: blog.id}%>

                        
                        <%end%>
                        
                        <div class="bg-light p-3" >
                          <%if comment_on_specific_blog(blog.id).count > 2 %>
                            
                            <div class = "mx-5 show-more-comment text-secondary" >View Previous comments</div>
                          <% end %>
                          <div class="my-3 ">
                          <% blogComments = []%>
                            <% comment_on_specific_blog(blog.id).each do |comments| %>
                            <% 
                              blogComments.push( comments.comment)

                            
                            %>
                            
                            <div class="container d-flex">
                              <div class ="row">
                                
                                <div class="col-md-12">
                                
                                  <a href="/profile/<%=find_UserbyCommentID(comments.user_id).username%>"><img src=<%=url_for(find_UserbyCommentID(comments.user_id).avatar)%>  class="profile-img-sm mx-4"></div></a>
                                </div>
                                
                                <div class="col-md-12 d-flex justify-content-between px-3 option " id="more-option-parent<%=comments.id%>">
                                
                                  <div  data-toggle="tooltip" data-placement="top" class="comment text-muted px-3" 
                                  title="By <%=find_UserbyCommentID(comments.user_id).username%>, on <%=comments.created_at.strftime('%b %d, %Y')%>">
                                  <%=comments.comment%></div>
                                  
                                  <div class=" show" id="more-option<%=comments.id%>">
                                    <div class="">
                                      <div  class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-chevron-circle-down text-secondary mx-3" ></i>
                                        <i class="fas fa-edit text-secondary mx-3"></i>
                                        <i class="fas fa-ellipsis-v text-secondary mx-3"></i>
                                      </div>

                                      <div class="dropdown-menu">
                                        <a class="dropdown-item" onclick="focus()" href="#">edit</a>
                                        <a class="dropdown-item" href="#">update</a>
                                        <a class="dropdown-item" href="#">delete</a>
                                      </div>
                                    </div>                                  
                                  </div>
                                </div>
                          
                              </div>
                            <% end %> 
                          <%if comment_on_specific_blog(blog.id).count > 2 %>
                            <div class=" mx-5 show-more-comment text-secondary my-4">View More Comments </div> 
                            <% end %>
                          </div>
                        </div>


<%=blogComments%>


                        <div >
                          <%if flash[:comment_saved]%>
                            <%flash[:comment_saved].each do |msg| %>
                              <div class="alert alert-success my-2">
                                <%= msg %>
                              </div>
                            <%end %>
                          <%end%>
                        </div>
                      </div>
                      
                  </div>
                </div>
              </div>
              <hr>
              <% end %> 
            </div>
          </div>
        </div>
      </div>
    </div>
    
    
  </div>
</div>

app/views/blog/new.html.erb
<%=render "form"%>

app/views/blog/search.html.erb
<div class ="pt-5 mt-5">

    <%if @searchedBlog.empty? %>
        <h2 class= "text-center">No any Blog found. Please try something else...</h2>
    <%else%>
        
        
            <% @searchedBlog.each do |blog| %>
                <div class="container">
                    <div class="display-5 ">
                        <%=link_to blog.blog_title, blog ,:class => "card card-inverse text-uppercase text-success text-decoration-none"%>
                        
                    </div>
                    <div><%=blog.created_at%></div>
                </div>
            <% end %>

        
    <%end%>
    <br>
   
    
</div>

app/views/blog/show.html.erb
<div class="container">

  
    <div class= "row ">

        <div class="col-md-12 bg-profile mt-5 pt-4" style="color:green; background-image:url('/assets/ruby_on_rails.jpg'); ">
   
            <div class="text-center p-5">

                
                <%if @user.avatar.nil?%>
                    <i class="rounded-circle border border-3 bg-light fa fa-user p-3 fa-3x"></i>
                    
                <%else%>
                    <img src="<%=url_for(@user.avatar)%>" class="rounded-circle border border-4 border-danger shadow"  height="150px" width="150px">
                      
                <%end
                %>
                

                <div class=""><strong class="badge bg-light text-dark"><%=@user.username%> (<%=@user.job%>)</strong>
                    <%#= image_tag url_for("blog.jpg")%>
                </div>  
                 <%#% <div>Email: <%=@user.email%>
                
                <div class="badge mx-1 bg-light text-light border " >
                    <a href="<%=@user.insta_link%>" class="text-success"><i class="fab fa-instagram"></i></a>
                    <a href="<%=@user.fb_link%>" class="text-success"><i class="fab fa-facebook"></i></a>
                    <a href="<%=@user.fb_link%>" class="text-success"><i class="fab fa-linkedin"></i></a>
                    <a href="<%=@user.fb_link%>" class="text-success"><i class="fab fa-stack-overflow"></i></a>

                </div>
            </div>    
        </div>

         <div class="bg-light shadow">
        <div class= "text-center display-1 "><p class="badge bg-info border"><%=@blog.blog_title%></p></div>
        <div class = "col-md-12">  
            <%=@blog.content%>  
        </div>
        <div class="fb-comments" data-href="http://localhost:3000/blog" data-width="700" data-numposts="0"></div>

    </div>
        
    </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css" integrity="sha512-Ez0cGzNzHR1tYAv56860NLspgUGuQw16GiOOp/I2LuTmpSK9xDXlgJz3XN4cnpXWDmkNBKXR/VDMTCnAaEooxA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
  </head>
  <body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v11.0&appId=471256000357095&autoLogAppEvents=1" nonce="GxgBsjHv"></script>
    <%=render "/partials/navbar"%>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/login/index.html.erb
<%=render "./partials/navbar"%>

<div class = "container">

    <div class = "row d-fex justify-content-center p-5 mt-5"  >
    
    
        <div class = "col-md-4 border p-4  shadow rounded bg-light ">
            <div class="d-flex justify-content-center">
                <i class="far fa-eye-slash bg-secondary  fa-2x rounded-circle text-light border shadow p-3 text-center"></i>
            </div>

            <hr>    

            
            <%= form_with url:{ action: :check_credentials } ,method: :post do |f| %>
                 <%= f.text_field :username, :class => "form-control", :placeholder =>"Username"%><br />
                 <%= f.password_field :password, :class => "form-control", :placeholder =>"Password" %><br />
                
                <%= f.submit "login", :class => "btn btn-outline-success"%>

            <% end %>
            <%if flash[:login_errors]%>
                <% flash[:login_errors].each do |msg| %>
                    <div class="alert alert-danger my-2">
                        <%= msg %>
                    </div>
                <% end %>
            <%end%>
            
            <%if flash[:logout_msg]%>
                <% flash[:logout_msg].each do |msg| %>
                    <div class="alert alert-success my-2">
                        <%= msg %>
                    </div>
                <% end %>
            <%end%>
            <%if flash[:user_created_msg]%>
                <% flash[:user_created_msg].each do |msg| %>
                    <div class="alert alert-success my-2">
                        <%= msg %>
                    </div>
                <% end %>
            <%end%>
        
        
        
        </div>
    
    </div>

</div>

app/views/partials/_like_comment_share.html.erb
<div >
  <div>
    <div class="d-flex justify-content-end my-3" >
      <button class="btn border border-info mx-5 likebutton"  id= "likebtn<%=blog_id%>">like</button>
      <button class="btn border border-info mx-5 cmntbutton" id= "cmntbtn<%=blog_id%>">comment</button>
      <div  class="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <button class="btn border border-success sharebutton" id= "sharebtn<%=blog_id%>" >share</button>
      </div>
      
      <div class="dropdown-menu border-success bg-light shadow">
        
        <div class="fb-share-button p-3" data-href="https://outblog.herokuapp.com/blogs" data-layout="button" data-size="small">
          <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Foutblog.herokuapp.com%2Fblogs&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore"></a>
        </div>
        
        <a class="dropdown-item" href="#">
          <div><script src="https://platform.linkedin.com/in.js" type="text/javascript">
              lang: en_US
            </script>
            <script type="IN/Share" data-url="https://outblog.herokuapp.com/blogs"></script></div>
        </a>
      </div>
    </div>
  </div>

  <div class ="d-none" id="comment-section<%=blog_id%>">
    <div id="comment_box" class= " bg-light shadow p-4">
      <div  class ="" id="comment-section<%=blog_id%>">
        <%= form_with model:Comment,url:{ action: :create_comment} do |form| %>
          <span >
            <div class="row">
              <div class="col-md-1">
                <img src=<%=url_for(current_user.avatar)%> class="profile">
              </div>
              <div class="col-md-9">
                <%=form.text_area :comment,:id=>"comment#{blog_id}",:class=>"form-control col-md-6 rounded",:placeholder=>"Write comment..."%>
              </div>
              <%=form.text_field :user_id, :type=>"hidden", :id=>"comment_user_id#{blog_id}", :value=>current_user.id %>
              <%=form.text_field :blog_id, :type=>"hidden",:id=>"comment_blog_id#{blog_id}", :value=>blog_id %>
              <div class="col-md-1">
                <%=form.submit "comment",:class=>"btn btn-outline-primary" %>
              </div>
            </div>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<%=current_user%>

<div class = " fixed-top ">
    <nav class="navbar navbar-expand-lg nav-color navbar-light shadow d-flex justifiy-content-center">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#"></a>
     
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link " href="/blog"><i class="fa fa-home fa-2x"></i> <span class="sr-only">(current)</span></a>
      </li>
       
      <%if session[:user_id].nil?%>
        <li class = "nav-item active">
        
            <a class = "nav-link btn btn-outline-light mx-2" href="/login" ><i class="fas fa-sign-in-alt"></i>login</a>
        </li>
        <li class = "nav-item active">
        
            <a class = "nav-link btn btn-outline-info mx-2" href="/register" ><i class="fas fa-user-plus"></i>sign up</a>
        </li>

       

        <%else%>
          <li class = "nav-item "><a class = "nav-link btn btn-none text-light " href="/profile/<%=current_user.username%>"> <img src=<%=url_for(current_user.avatar)%> class="profile"><%=current_user.username%></a></li>
       
          <li class = "nav-item "><a class = "nav-link btn btn-outline-danger text-light " href="/logout" method="get" action="logout"><i class="fas fa-sign-out-alt"></i>logout</a></li>
        
        <%end %>
      <li>
          <div class = "d-flex mx-4">
              <div><%= form_with url: "/search", method: :get do |form| %></div>
               <%#= form.label :query, :class =>"" %>
                <div> <%= form.text_field :query ,:placeholder=>"Search Blogs",:class=>"form-control"%></div>
                 <div><%= form.submit "Search",:class=>"btn btn-outline-success  mx-2" %> </div>
              <% end %>
            
          </div>
        </li>
        <li>
        <div class="toggle-button">
            <p id="toggle-label-dark">Dark Mode</p>
            <p id="toggle-label-light">Light Mode</p>
            <label>
              <input type="checkbox" id="theme-toggler" />
              <span class="check"></span>
            </label>
          </div>
        </div>




        </li>
    </ul>
    
  </div>
</nav>
</div>  